### ISSUE TITLE
Developer Install - ".[dev]" 

### ISSUE THREAD

**Issue by alec-flowers** [matthieumeo/pyxu#17]
$ python3 -m pip install -e ".[dev]"
On this command of the developer install, pip was searching for over an hour on determining ipython compatibility. 

A fix that work was suggested by Joan which replaces this command: conda create -n pycsou --channel=conda-forge --file=conda/requirements.txt
with: conda create -n pycsou --file=conda/requirements.txt -c conda-forge python=3.9

**Comment by SepandKashani** [comment]
The installation speed via `pip` is a known problem. It is the method described in the README at the moment because someone with no knowledge of python/conda can get a working install of pycsou from PyPI.
Ultimately we need to create dedicated conda packages for pycsou which target Python3.8+.

A task to add to the roadmap...
